INSERT INTO album (album_id, album_name) VALUES (1, "Comedy");
INSERT INTO album (album_id, album_name) VALUES (2, "Ghost (Acoustic)");
INSERT INTO album (album_id, album_name) VALUES (3, "To Begin Again");
INSERT INTO album (album_id, album_name) VALUES (4, "Crazy Rich Asians (Original Motion Picture Soundtrack)");
INSERT INTO album (album_id, album_name) VALUES (5, "Hold On");
INSERT INTO album (album_id, album_name) VALUES (6, "Days I Will Remember");
INSERT INTO album (album_id, album_name) VALUES (7, "Is There Anybody Out There?");
INSERT INTO album (album_id, album_name) VALUES (8, "We Sing. We Dance. We Steal Things.");
INSERT INTO album (album_id, album_name) VALUES (9, "Hunger");
INSERT INTO album (album_id, album_name) VALUES (10, "Episode");
INSERT INTO album (album_id, album_name) VALUES (11, "Love Is a Four Letter Word");
INSERT INTO album (album_id, album_name) VALUES (12, "Solo");
INSERT INTO album (album_id, album_name) VALUES (13, "Bad Liar");
INSERT INTO album (album_id, album_name) VALUES (14, "Hold On (Remix)");
INSERT INTO album (album_id, album_name) VALUES (15, "The Boy Who Never");
INSERT INTO album (album_id, album_name) VALUES (16, "ily (i love you baby)");
INSERT INTO album (album_id, album_name) VALUES (17, "At My Worst");
INSERT INTO album (album_id, album_name) VALUES (18, "Cover Sessions, Vol. 4");
INSERT INTO album (album_id, album_name) VALUES (19, "Cover Sessions, Vol. 3");
INSERT INTO album (album_id, album_name) VALUES (20, "Is There Anybody Out There? - Track by Track Commentary");
INSERT INTO album (album_id, album_name) VALUES (21, "Coffee Moment");
INSERT INTO album (album_id, album_name) VALUES (22, "Human - Best Adult Pop Tunes");
INSERT INTO album (album_id, album_name) VALUES (23, "Mellow Adult Pop");
INSERT INTO album (album_id, album_name) VALUES (24, "Holly Jolly Christmas");
INSERT INTO album (album_id, album_name) VALUES (25, "Feeling Good - Adult Pop Favorites");
INSERT INTO album (album_id, album_name) VALUES (26, "Christmas Time");
INSERT INTO album (album_id, album_name) VALUES (27, "Perfect Christmas Hits");
INSERT INTO album (album_id, album_name) VALUES (28, "Merry Christmas");
INSERT INTO album (album_id, album_name) VALUES (29, "Christmas Music - Holiday Hits");
INSERT INTO album (album_id, album_name) VALUES (30, "Christmas Country Songs 2022");
INSERT INTO album (album_id, album_name) VALUES (31, "Mellow Bars R'n'B");
INSERT INTO album (album_id, album_name) VALUES (32, "Chill Christmas Dinner");
INSERT INTO album (album_id, album_name) VALUES (33, "rainy day indie");
INSERT INTO album (album_id, album_name) VALUES (34, "sadsadchristmas");
INSERT INTO album (album_id, album_name) VALUES (35, "Mega Hits Autumn/Fall 2022");
INSERT INTO album (album_id, album_name) VALUES (36, "Country Car Hits");
INSERT INTO album (album_id, album_name) VALUES (37, "Country Road Songs");
INSERT INTO album (album_id, album_name) VALUES (38, "Finest Country");
INSERT INTO album (album_id, album_name) VALUES (39, "Easy Country");
INSERT INTO album (album_id, album_name) VALUES (40, "Cozy Country");
INSERT INTO album (album_id, album_name) VALUES (41, "Good Times Country");
INSERT INTO album (album_id, album_name) VALUES (42, "Laidback Country");
INSERT INTO album (album_id, album_name) VALUES (43, "Chillin' It - Mellow Day Country");
INSERT INTO album (album_id, album_name) VALUES (44, "Trampoline (Acoustic)");
INSERT INTO album (album_id, album_name) VALUES (45, "Documentary");
INSERT INTO album (album_id, album_name) VALUES (46, "Black Bear");
INSERT INTO album (album_id, album_name) VALUES (47, "The Bedroom Demos");
INSERT INTO album (album_id, album_name) VALUES (48, "So Far Away (Acoustic)");
INSERT INTO album (album_id, album_name) VALUES (49, "Build It Better");
INSERT INTO album (album_id, album_name) VALUES (50, "Sleepwalking in the Rain");
INSERT INTO album (album_id, album_name) VALUES (51, "Little Voice");
INSERT INTO album (album_id, album_name) VALUES (52, "What's Left of You");
INSERT INTO album (album_id, album_name) VALUES (53, "Pano");
INSERT INTO album (album_id, album_name) VALUES (54, "The Daylight EP");
INSERT INTO album (album_id, album_name) VALUES (55, "Montage Of Heck: The Home Recordings");
INSERT INTO album (album_id, album_name) VALUES (56, "Covers");
INSERT INTO album (album_id, album_name) VALUES (57, "Midnight Waves");
INSERT INTO album (album_id, album_name) VALUES (58, "Making All Things New");
INSERT INTO album (album_id, album_name) VALUES (59, "What's Inside: Songs from Waitress");
INSERT INTO album (album_id, album_name) VALUES (60, "In My Veins (Feat. Erin Mccarley)");
INSERT INTO album (album_id, album_name) VALUES (61, "Under Covers");
INSERT INTO album (album_id, album_name) VALUES (62, "Whatever It Takes");
INSERT INTO album (album_id, album_name) VALUES (63, "America Town");
INSERT INTO album (album_id, album_name) VALUES (64, "Dive Deep");
INSERT INTO album (album_id, album_name) VALUES (65, "You're Still The One");
INSERT INTO album (album_id, album_name) VALUES (66, "It Doesn't Have To Make Sense");
INSERT INTO album (album_id, album_name) VALUES (67, "When the Morning Comes");
INSERT INTO album (album_id, album_name) VALUES (68, "Eat, Pray, Love");
INSERT INTO album (album_id, album_name) VALUES (69, "Good Light");
INSERT INTO album (album_id, album_name) VALUES (70, "Know.");
INSERT INTO album (album_id, album_name) VALUES (71, "Break Up Songs");
INSERT INTO album (album_id, album_name) VALUES (72, "Into The Wild (Music For The Motion Picture)");
INSERT INTO album (album_id, album_name) VALUES (73, "u don't deserve me");
INSERT INTO album (album_id, album_name) VALUES (74, "The Blessed Unrest");
INSERT INTO album (album_id, album_name) VALUES (75, "Slow Christmas Songs 2022");
INSERT INTO album (album_id, album_name) VALUES (76, "Lonely Christmas 2022");
INSERT INTO album (album_id, album_name) VALUES (77, "Bookmarks");
INSERT INTO album (album_id, album_name) VALUES (78, "Alternative Christmas 2022");
INSERT INTO album (album_id, album_name) VALUES (79, "Acoustic Christmas Campfire");
INSERT INTO album (album_id, album_name) VALUES (80, "Del gusto de mam�");
INSERT INTO album (album_id, album_name) VALUES (81, "OO's Music Grandi Successi");
