INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (1, 'The Daily 31', 'Comedy', 'grow', 107, 'Australia', 557941, 592427);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (2, 'The Happiness Lab 46', 'Society & Culture', 'run', 106, 'Germany', 923375, 2169145);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (3, 'Song Exploder 94', 'Science', 'believe', 75, 'Canada', 32381, 4482799);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (4, 'Stuff You Should Know 73', 'History', 'dream', 176, 'USA', 315070, 2255270);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (5, 'Stuff You Should Know 25', 'Music', 'dream', 51, 'UK', 544648, 4955160);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (6, 'Reply All 17', 'True Crime', 'hope', 35, 'USA', 178447, 1963440);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (7, 'Call Your Girlfriend 42', 'Science', 'believe', 44, 'South Korea', 822362, 433965);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (8, 'Serial 1', 'Music', 'believe', 135, 'Canada', 504806, 1958547);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (9, 'The Daily 59', 'Business', 'hope', 39, 'South Korea', 66746, 3830436);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (10, 'The Happiness Lab 91', 'Music', 'love', 39, 'India', 897803, 3057240);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (11, 'The Daily 51', 'Business', 'hope', 162, 'South Korea', 119645, 1370265);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (12, 'Radiolab 79', 'History', 'love', 120, 'Canada', 671850, 90229);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (13, 'Crime Junkie 41', 'Technology', 'fight', 75, 'Australia', 240606, 4767999);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (14, 'The Tim Ferriss Show 68', 'Technology', 'run', 155, 'South Korea', 270781, 4586913);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (15, 'Freakonomics Radio 63', 'Society & Culture', 'fight', 65, 'South Korea', 565732, 1469158);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (16, 'Crime Junkie 94', 'History', 'run', 64, 'Germany', 683382, 2050735);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (17, 'TED Talks Daily 96', 'Science', 'believe', 23, 'Brazil', 568689, 2110843);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (18, 'How I Built This 85', 'True Crime', 'shine', 45, 'South Korea', 894639, 2674289);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (19, 'How I Built This 36', 'Society & Culture', 'run', 105, 'South Korea', 609580, 4631956);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (20, 'The Tim Ferriss Show 61', 'History', 'fly', 165, 'USA', 219723, 1069451);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (21, 'Planet Money 84', 'Business', 'believe', 30, 'Brazil', 580075, 2424854);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (22, 'The Moth 21', 'Comedy', 'fight', 165, 'Australia', 767317, 1637052);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (23, 'Code Switch 27', 'History', 'learn', 99, 'South Korea', 792189, 3488718);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (24, 'The Tim Ferriss Show 30', 'Music', 'run', 88, 'Canada', 151381, 401696);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (25, 'TED Talks Daily 98', 'True Crime', 'believe', 68, 'Australia', 822612, 2450637);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (26, 'TED Talks Daily 50', 'True Crime', 'dream', 100, 'Germany', 901000, 176340);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (27, 'Planet Money 61', 'Business', 'run', 121, 'India', 578056, 2814126);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (28, 'Hardcore History 58', 'Business', 'grow', 163, 'South Korea', 699798, 1773961);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (29, 'The Daily 51', 'Education', 'believe', 155, 'France', 105032, 1380447);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (30, 'Serial 53', 'True Crime', 'grow', 118, 'India', 427329, 1350778);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (31, 'Armchair Expert 17', 'News', 'run', 177, 'France', 243868, 4449272);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (32, 'The Breakfast Club 78', 'Business', 'love', 35, 'France', 499278, 3923146);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (33, 'Hardcore History 82', 'Science', 'love', 43, 'India', 403614, 3868084);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (34, 'The Tim Ferriss Show 89', 'Business', 'dream', 21, 'UK', 898368, 227529);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (35, 'The Breakfast Club 51', 'Technology', 'dream', 43, 'UK', 662952, 4944908);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (36, 'Code Switch 58', 'News', 'fly', 75, 'India', 778746, 206385);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (37, 'Planet Money 96', 'History', 'hope', 109, 'Germany', 907871, 2838745);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (38, 'Armchair Expert 32', 'Technology', 'love', 111, 'Australia', 199037, 2271209);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (39, 'Crime Junkie 90', 'Comedy', 'hope', 163, 'India', 974003, 4182986);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (40, 'The Tim Ferriss Show 93', 'Education', 'shine', 128, 'France', 158387, 4920135);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (41, '99% Invisible 22', 'Business', 'run', 14, 'Germany', 108871, 2008710);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (42, 'TED Talks Daily 14', 'Music', 'hope', 64, 'India', 558051, 3509609);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (43, 'Philosophize This! 19', 'Music', 'hope', 138, 'USA', 909355, 987843);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (44, 'The Happiness Lab 98', 'History', 'grow', 167, 'Germany', 585267, 2644032);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (45, 'Serial 75', 'Technology', 'shine', 12, 'Germany', 471710, 1692520);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (46, 'Reply All 30', 'Society & Culture', 'grow', 39, 'Germany', 796739, 4951955);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (47, 'Call Your Girlfriend 30', 'Technology', 'run', 154, 'India', 386204, 1159278);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (48, 'The Breakfast Club 26', 'Music', 'believe', 141, 'Germany', 703691, 3889059);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (49, 'Code Switch 99', 'Society & Culture', 'fight', 93, 'Germany', 830968, 4163294);
INSERT INTO podcasts (podcast_id, podcast_name, genre, lyrics, duration, country, like_count, listen_count) VALUES (50, 'The Moth 62', 'Education', 'dream', 41, 'UK', 164096, 306302);
